name: Build And Test

on:
# Disabled until I figured out how to start docker-compse in the GitHub Actions
#  pull_request:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build And Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.3.0

      - name: Restore Gradle Build Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Clean Assemble with Gradle
        run: ./gradlew clean assemble

      - name: Run Unit Tests
        run: ./gradlew test --build-cache
